services:
  database:
    container_name: database
    image: postgres:16
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - ".env"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 5
  
  backend:
    container_name: backend
    build: ./
    env_file:
      - ".env"
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy



volumes:
  pg_data: